docker:
  image: yegor256/java8

architect:
  - sizovs

assets:
  gradle.properties: "sizovs/secrets#gradle.properties"

release:
  script: |-
    mv ../gradle.properties .
    ./gradlew --info --no-daemon --stacktrace --console=plain jar mavenCentralSync -Pversion=${tag}